# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_verbose_name_plural_for_calendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'permissions': (('view_calendar', 'Can view calendars'),), 'verbose_name': 'calendar', 'verbose_name_plural': 'calendars'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('view_event', 'Can view events'),), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'permissions': (('view_occurrence', 'Can view occurrences'),), 'verbose_name': 'occurrence', 'verbose_name_plural': 'occurrences'},
        ),
        migrations.AddField(
            model_name='occurrence',
            name='occurrence_color',
            field=models.CharField(blank=True, max_length=10, verbose_name='occurrence color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='color_event',
            field=models.CharField(max_length=10, verbose_name='Color event'),
        ),
    ]
